/** Legacy Vite route segments (pre `/app` prefix) — for docs / tooling only */
export const routeParity = [
  "/",
  "/about",
  "/login",
  "/signup",
  "/forgot-password",
  "/dashboard",
  "/resume",
  "/jobs",
  "/auto-apply",
  "/interview",
  "/tracker",
  "/negotiation",
  "/legal",
  "/coding-arena",
  "/credits",
  "/profile",
  "/settings",
  "/admin/dashboard",
  "/admin/jobs",
  "/admin/publish",
  "/admin/applications",
  "/admin/candidates",
  "/admin/analytics",
  "/admin/plans",
  "/admin/settings",
] as const;
